version: '3'
services:
  mevir-estimacion-inscripcion:
    restart: always
    image: 192.168.100.55:5000/mevir_estimacion_inscripcion:0.0.1
    ports:
      - 5233:80
    volumes:
      - ./Datos:/usr/share/nginx/html/mevir-estimacion-inscripcion/Datos
      - ./Modelos:/usr/share/nginx/html/mevir-estimacion-inscripcion/Modelos
